"""Direct equality-constraint learning with negative-sample augmentation.

This is the only non-GP experiment file kept in this folder.
It learns an implicit function h(x, y) directly from:
1. positive samples on the target zero-set
2. negative samples generated by normal-direction augmentation

Use this file when you want to study the "augment negatives, then fit h=0"
pipeline without Gaussian Process machinery.
"""

from pathlib import Path

import numpy as np
import torch, torch.nn as nn, torch.nn.functional as F, torch.optim as optim
import matplotlib.pyplot as plt
from typing import Callable, Dict, List, Tuple

# ---------------- Config ----------------
SEED         = 123
GRID_LIM     = 1.8           # viewport: [-GRID_LIM, GRID_LIM]^2
GRID_N       = 240           # grid resolution for contouring & chamfer
NPOS         = 20
NNEG         = 40
EPOCHS_NN    = 500
EPOCHS_POLY  = 300
BATCH        = 512
LR_NN        = 1e-3
LR_POLY      = 5e-3
MARGIN       = 0.10          # softplus margin target (smaller => smoother)
ALPHA_NEG    = 0.4           # weight on negative loss
LAMBDA_L2    = 1e-4
LAMBDA_GRAD  = 0.5e-3
# scale-invariant metric hyperparams
TAU_DIST     = 0.03          # tolerated geometric distance on data (NRD)
SIGMA_GEOM   = 0.06          # chamfer->score scale
ALPHA_FINAL  = 0.5           # blend DataSat & Geom scores
OUT_DIR      = Path(__file__).resolve().parent / "results"

# ----- choose constraint here -----
CONSTRAINT_NAME = "ellipse"   # "circle" | "ellipse" | "line" | "parabola"

np.random.seed(SEED); torch.manual_seed(SEED)

# ---------------- Constraint factory ----------------
def make_constraint(name: str):
    name = name.lower()
    if name == "circle":
        def h_np(P):
            x, y = P[...,0], P[...,1]
            return x*x + y*y - 1.0
        def grad_np(P):
            x, y = P[...,0], P[...,1]
            g = np.stack([2*x, 2*y], axis=-1)
            n = np.linalg.norm(g, axis=-1, keepdims=True) + 1e-9
            return g / n
        def gt_samples(n=2000):
            t = np.random.uniform(0, 2*np.pi, n)
            return np.stack([np.cos(t), np.sin(t)], axis=1)
        def gt_curve(M=800):
            t = np.linspace(0, 2*np.pi, M, endpoint=False)
            return np.stack([np.cos(t), np.sin(t)], axis=1)
    elif name == "ellipse":
        a, b, theta = 1.2, 0.7, np.deg2rad(30.0)
        R = np.array([[np.cos(theta), -np.sin(theta)],
                      [np.sin(theta),  np.cos(theta)]])
        R_inv = R.T
        def h_np(P):
            Q = P @ R_inv.T
            X, Y = Q[...,0], Q[...,1]
            return (X/a)**2 + (Y/b)**2 - 1.0
        def grad_np(P):
            Q = P @ R_inv.T
            X, Y = Q[...,0], Q[...,1]
            gQ = np.stack([2*X/(a*a), 2*Y/(b*b)], axis=-1)
            g = gQ @ R_inv  # chain rule
            n = np.linalg.norm(g, axis=-1, keepdims=True) + 1e-9
            return g / n
        def gt_samples(n=2000):
            t = np.random.uniform(0, 2*np.pi, n)
            Q = np.stack([a*np.cos(t), b*np.sin(t)], axis=1)
            return Q @ R.T
        def gt_curve(M=800):
            t = np.linspace(0, 2*np.pi, M, endpoint=False)
            Q = np.stack([a*np.cos(t), b*np.sin(t)], axis=1)
            return Q @ R.T
    elif name == "line":
        def h_np(P):
            x, y = P[...,0], P[...,1]
            return x + y - 1.0
        def grad_np(P):
            g = np.array([1.0,1.0], dtype=float)
            g = np.broadcast_to(g, P.shape)
            n = np.linalg.norm(g, axis=-1, keepdims=True) + 1e-9
            return g / n
        def gt_samples(n=2000):
            xs = np.random.uniform(-GRID_LIM, GRID_LIM, n)
            ys = 1.0 - xs
            mask = (np.abs(ys) <= GRID_LIM)
            xs, ys = xs[mask], ys[mask]
            return np.stack([xs, ys], axis=1)
        def gt_curve(M=800):
            xs = np.linspace(-GRID_LIM, GRID_LIM, M)
            ys = 1.0 - xs
            mask = (np.abs(ys) <= GRID_LIM)
            return np.stack([xs[mask], ys[mask]], axis=1)
    elif name == "parabola":
        def h_np(P):
            x, y = P[...,0], P[...,1]
            return y - (0.5*x*x - 0.2)
        def grad_np(P):
            x, y = P[...,0], P[...,1]
            g = np.stack([-x, np.ones_like(x)], axis=-1)
            n = np.linalg.norm(g, axis=-1, keepdims=True) + 1e-9
            return g / n
        def gt_samples(n=2000):
            xs = np.random.uniform(-1.6, 1.6, n)
            ys = 0.5*xs*xs - 0.2
            mask = (np.abs(ys) <= GRID_LIM)
            xs, ys = xs[mask], ys[mask]
            return np.stack([xs, ys], axis=1)
        def gt_curve(M=800):
            xs = np.linspace(-1.6, 1.6, M)
            ys = 0.5*xs*xs - 0.2
            mask = (np.abs(ys) <= GRID_LIM)
            return np.stack([xs[mask], ys[mask]], axis=1)
    else:
        raise ValueError(f"Unknown constraint: {name}")
    return h_np, grad_np, gt_samples, gt_curve

h_gt_np, grad_gt_np, gt_samples_fn, gt_curve_fn = make_constraint(CONSTRAINT_NAME)

# ---------------- Data (pos/neg) ----------------
def sample_positive(n):
    return gt_samples_fn(n)

def sample_negative_from_normals(pos_pts, std=0.15, ratio_inner_outer=0.5):
    """
    对正样本沿 GT 法向做内/外扰动，生成负样本。线/抛物在局部法向上“左右”偏移。
    """
    P = pos_pts
    N = grad_gt_np(P)            # unit normal of GT h at P
    eps = np.random.normal(0.0, std, size=(P.shape[0], 1))
    P_out = P + np.abs(eps) * N
    P_in  = P - np.abs(eps) * N
    Q = np.concatenate([P_out, P_in], axis=0)
    mask = np.abs(h_gt_np(Q)) > 1e-3  # remove points too close to zero-set
    Q = Q[mask]
    return Q

pos_np = sample_positive(NPOS)
neg_pool = sample_negative_from_normals(sample_positive(NNEG), std=0.12)
np.random.shuffle(neg_pool)
neg_np = neg_pool[:NNEG]

pos = torch.tensor(pos_np, dtype=torch.float32)
neg = torch.tensor(neg_np, dtype=torch.float32)

# ---------------- Models ----------------
class MLPImplicit(nn.Module):
    def __init__(self, in_dim=2, hidden=16, layers=2):
        super().__init__()
        net = []
        last = in_dim
        for _ in range(layers):
            net += [nn.Linear(last, hidden), nn.Tanh()]
            last = hidden
        net += [nn.Linear(last, 1)]
        self.net = nn.Sequential(*net)
    def forward(self, x):
        return self.net(x).squeeze(-1)

class PolyImplicit(nn.Module):
    def __init__(self, degree=2):
        super().__init__()
        self.degree = degree
        self.M = sum(1 for d in range(degree+1) for _ in range(d+1))
        self.w = nn.Parameter(torch.randn(self.M)*0.01)
    def forward(self, x):
        Phi = poly_features(x, self.degree)
        return (Phi @ self.w).squeeze(-1)

def poly_features(x, degree):
    N = x.shape[0]
    feats = [torch.ones(N, 1, dtype=x.dtype, device=x.device)]
    for d in range(1, degree+1):
        for i in range(d+1):
            j = d - i
            feats.append((x[:, :1]**i) * (x[:, 1:]**j))
    return torch.cat(feats, dim=1)

# ---------------- Regularizers ----------------
def param_l2(model):
    return sum((p**2).sum() for p in model.parameters())

def grad_norm_penalty(model, xs, target_norm=1.0):
    xs = xs.detach().clone().requires_grad_(True)
    vals = model(xs)
    grad = torch.autograd.grad(vals.sum(), xs, create_graph=False)[0]
    return ((grad.norm(dim=1) - target_norm)**2).mean()

# ---------------- Training (4 loss variants) ----------------
def train_one(model, variant=1, epochs=300, lr=1e-3,
              batch=BATCH, margin=MARGIN, alpha=ALPHA_NEG,
              lam_l2=LAMBDA_L2, lam_grad=LAMBDA_GRAD):
    opt = optim.Adam(model.parameters(), lr=lr)
    losses = []
    Np, Nn = pos.shape[0], neg.shape[0]
    for ep in range(epochs):
        idx_p = torch.randint(0, Np, (batch,))
        xb_p = pos[idx_p]
        hp = model(xb_p)
        loss = hp.abs().mean()  # POS

        if variant == 2:
            idx_n = torch.randint(0, Nn, (batch,))
            xb_n = neg[idx_n]
            hn = model(xb_n)
            loss = loss + alpha * F.softplus(margin - hn.abs()).mean()

        if variant == 3:
            loss = loss + lam_l2 * param_l2(model)

        if variant == 4:
            loss = loss + lam_grad * grad_norm_penalty(model, xb_p)

        opt.zero_grad(); loss.backward(); opt.step()
        losses.append(loss.item())
    return model, np.array(losses)

# ---------------- Metrics (scale-invariant) ----------------
def normalized_distance(model, X, grad_floor=1e-6, batch=4096):
    out = []
    n = X.shape[0]
    for i in range(0, n, batch):
        xb = X[i:i+batch].detach().clone().requires_grad_(True)
        hb = model(xb)
        grad = torch.autograd.grad(hb.sum(), xb, create_graph=False)[0]
        dn = hb.abs() / (grad.norm(dim=1) + grad_floor)
        out.append(dn.detach().cpu().numpy())
    return np.concatenate(out, axis=0)

def data_sat_score(model, pos_tensor, tau=TAU_DIST):
    dhat = normalized_distance(model, pos_tensor)
    return float((dhat <= tau).mean()), dhat

def grid_zero_contour_points(model, grid_lim=GRID_LIM, N=GRID_N):
    xs = np.linspace(-grid_lim, grid_lim, N)
    ys = np.linspace(-grid_lim, grid_lim, N)
    XX, YY = np.meshgrid(xs, ys)
    P = np.stack([XX.ravel(), YY.ravel()], axis=1).astype(np.float32)
    with torch.no_grad():
        ZZ = model(torch.from_numpy(P)).cpu().numpy().reshape(N, N)

    fig, ax = plt.subplots()
    cs = ax.contour(XX, YY, ZZ, levels=[0.0])
    plt.close(fig)

    seglists = getattr(cs, "allsegs", None)
    if not seglists or len(seglists) == 0:
        return np.zeros((0, 2))
    level_segs = seglists[0]
    if len(level_segs) == 0:
        return np.zeros((0, 2))
    return np.concatenate(level_segs, axis=0)


def chamfer_symmetric(A, B):
    """ mean min dist A->B + mean min dist B->A """
    if A.shape[0]==0 or B.shape[0]==0:
        return np.inf
    d2 = ((A[:,None,:]-B[None,:,:])**2).sum(-1)
    da = np.sqrt(d2.min(axis=1)).mean()
    db = np.sqrt(d2.min(axis=0)).mean()
    return (da + db) * 0.5

def geometry_chamfer_score(model, gt_curve_pts, sigma=SIGMA_GEOM):
    pred_pts = grid_zero_contour_points(model)
    cd = chamfer_symmetric(pred_pts, gt_curve_pts)
    if not np.isfinite(cd): return 0.0, cd
    score = float(np.exp(-cd / sigma))
    return score, cd

# ---------------- Visualization helpers ----------------
def plot_levelset(ax, model, title, overlay_gt=False, show_data=True):
    xs = np.linspace(-GRID_LIM, GRID_LIM, GRID_N)
    ys = np.linspace(-GRID_LIM, GRID_LIM, GRID_N)
    XX, YY = np.meshgrid(xs, ys)
    P = np.stack([XX.ravel(), YY.ravel()], axis=1).astype(np.float32)
    with torch.no_grad():
        ZZ = model(torch.from_numpy(P)).cpu().numpy().reshape(GRID_N, GRID_N)
    cs = ax.contour(XX, YY, ZZ, levels=[0.0], colors='black', linewidths=4)
    ax.contour(XX, YY, ZZ, levels=np.arange(-0.1, 0.1, 0.01), cmap="coolwarm", linewidths=1.2)

    if overlay_gt:
        gt = gt_curve_fn(M=1000)
        ax.plot(gt[:,0], gt[:,1], 'k--', lw=1, label='GT')

    if show_data:
        ax.scatter(pos_np[:,0], pos_np[:,1], s=7, color='green', alpha=1, label='positive')
        ax.scatter(neg_np[:,0], neg_np[:,1], s=3, color='red',   alpha=0.3, label='negative')
        if not getattr(ax, 'legend_added', False):
            ax.legend(loc='lower right', fontsize=6)
            ax.legend_added = True

    ax.set_aspect('equal')
    ax.set_xlim([-GRID_LIM, GRID_LIM])
    ax.set_ylim([-GRID_LIM, GRID_LIM])
    ax.set_title(title)
    ax.set_xlabel('x')
    ax.set_ylabel('y')


def plot_curve(ax, curve, title):
    ax.plot(curve); ax.set_title(title); ax.set_xlabel("Epoch"); ax.set_ylabel("Loss")

# ---------------- Customizable model grid ----------------
# Each entry defines one *row* in the visualization grid (Fig A & heatmap)
# You can mix NN and Polynomial models freely.
# Keys:
#   type: "nn" or "poly"
#   name: str (row label)
#   For type=="nn":     hidden (int), layers (int), epochs (int|None), lr (float|None)
#   For type=="poly":   degree (int), epochs (int|None), lr (float|None)
ARCH_CONFIGS: List[Dict] = [
    {"type":"nn",   "name":"NN(4x4)",     "hidden":4,  "layers":2, "epochs":EPOCHS_NN,   "lr":LR_NN},
    {"type":"nn",   "name":"NN(16x16)",   "hidden":16, "layers":2, "epochs":EPOCHS_NN,   "lr":LR_NN},
    {"type": "poly", "name": "Hyperplane", "degree": 1, "epochs": EPOCHS_POLY, "lr": LR_POLY},
    {"type":"poly", "name":"Ellipse", "degree":2,               "epochs":EPOCHS_POLY, "lr":LR_POLY},
    {"type":"poly", "name":"Poly(deg=3)", "degree":3,               "epochs":EPOCHS_POLY, "lr":LR_POLY},
]

# Loss grid (columns)
LOSS_VARIANTS = [
    (1, "POS"),
    (2, "POS+NEG(sp)"),
    (3, "POS+L2"),
    (4, "POS+GRAD"),
]


def make_model_from_cfg(cfg: Dict) -> Tuple[str, Callable[[], nn.Module], int, float]:
    """Return (name, constructor, epochs, lr) for a single row."""
    t = cfg["type"].lower()
    name = cfg.get("name")
    if t == "nn":
        hidden = int(cfg.get("hidden", 16))
        layers = int(cfg.get("layers", 2))
        epochs = int(cfg.get("epochs", EPOCHS_NN))
        lr = float(cfg.get("lr", LR_NN))
        def ctor():
            return MLPImplicit(hidden=hidden, layers=layers)
        if name is None:
            name = f"NN({hidden}x{hidden})x{layers}"
        return name, ctor, epochs, lr
    elif t == "poly":
        degree = int(cfg.get("degree", 2))
        epochs = int(cfg.get("epochs", EPOCHS_POLY))
        lr = float(cfg.get("lr", LR_POLY))
        def ctor():
            return PolyImplicit(degree=degree)
        if name is None:
            name = f"Poly(deg={degree})"
        return name, ctor, epochs, lr
    else:
        raise ValueError(f"Unknown model type in ARCH_CONFIGS: {t}")

# Build arch list from configs
archs = [ make_model_from_cfg(cfg) for cfg in ARCH_CONFIGS ]
loss_variants = LOSS_VARIANTS

# ---------------- Train all combos ----------------
results = {}
for arch_name, make_model, epochs, lr in archs:
    for vid, vname in loss_variants:
        model = make_model()
        model, curve = train_one(model, variant=vid, epochs=epochs, lr=lr)
        results[(arch_name, vname)] = (model, curve)

OUT_DIR.mkdir(parents=True, exist_ok=True)

# -------- Figure C: samples + GT curve overlay --------
plt.figure(figsize=(5,5))
plt.scatter(pos_np[:,0], pos_np[:,1], s=6, alpha=0.6, label="positive (on GT)")
plt.scatter(neg_np[:,0], neg_np[:,1], s=6, alpha=0.6, label="negative (normal offsets)")
# **GT overlay**
gt = gt_curve_fn(M=1000)
plt.plot(gt[:,0], gt[:,1], 'k--', lw=1.2, label=f"GT: {CONSTRAINT_NAME}")
plt.axis('equal'); plt.legend(); plt.title("Positive & Negative samples (with GT)")
plt.xlabel("x"); plt.ylabel("y")
plt.savefig(OUT_DIR / "dataaug_samples.png", dpi=180)

# -------- Figure A: (rows x cols) level-sets --------
R, C = len(archs), len(loss_variants)
figA, axesA = plt.subplots(R, C, figsize=(4*C, 4*R))
if R == 1 and C == 1:
    axes_iter = np.array([[axesA]])
elif R == 1:
    axes_iter = np.array([axesA])
elif C == 1:
    axes_iter = np.array([[ax] for ax in axesA])
else:
    axes_iter = axesA

for r, (arch_name, _, _, _) in enumerate(archs):
    for c, (_, vname) in enumerate(loss_variants):
        ax = axes_iter[r, c]
        model, _ = results[(arch_name, vname)]
        plot_levelset(ax, model, f"{arch_name} | {vname} | {CONSTRAINT_NAME}", overlay_gt=True, show_data=True)
figA.tight_layout()
figA.savefig(OUT_DIR / "dataaug_levelsets_grid.png", dpi=200)

# -------- Metrics & Heatmap --------
arch_names = [a[0] for a in archs]
loss_names = [v[1] for v in loss_variants]

data_sat_mat   = np.zeros((len(archs), len(loss_variants)))
geom_score_mat = np.zeros((len(archs), len(loss_variants)))
final_mat      = np.zeros((len(archs), len(loss_variants)))
chamfer_mat    = np.zeros_like(final_mat)

gt_dense = gt_curve_fn(M=1200)

for r, arch in enumerate(arch_names):
    for c, loss in enumerate(loss_names):
        model, _ = results[(arch, loss)]
        ds, _ = data_sat_score(model, pos, tau=TAU_DIST)
        gs, cd = geometry_chamfer_score(model, gt_dense, sigma=SIGMA_GEOM)

        data_sat_mat[r, c]   = ds
        geom_score_mat[r, c] = gs
        chamfer_mat[r, c]    = cd
        final_mat[r, c]      = (ds**ALPHA_FINAL) * (gs**(1-ALPHA_FINAL))

plt.figure(figsize=(8.2,6.2))
im = plt.imshow(final_mat, vmin=0.0, vmax=1.0, cmap="viridis")
for i in range(final_mat.shape[0]):
    for j in range(final_mat.shape[1]):
        txt = f"{final_mat[i,j]:.2f}\nDS:{data_sat_mat[i,j]:.2f}\nGS:{geom_score_mat[i,j]:.2f}"
        plt.text(j, i, txt, ha='center', va='center', color='w', fontsize=8)
plt.xticks(range(len(loss_names)), loss_names, rotation=20)
plt.yticks(range(len(arch_names)), arch_names)
plt.colorbar(im, label="FinalScore")
plt.title(f"Scale-invariant accuracy heatmap  |  GT: {CONSTRAINT_NAME}")
plt.tight_layout()
plt.savefig(OUT_DIR / "dataaug_score_heatmap.png", dpi=220)
plt.show()

print("Done.")
